name: justipin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  gap: ^3.0.1
  hugeicons: ^0.0.7
  introduction_screen: ^3.1.14
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3 # Untuk caching gambar peta jika diambil dari URL
  flutter_svg: ^1.1.6          # Untuk mendukung gambar format SVG
  lottie: ^1.4.3               # Untuk animasi ilustrasi (opsional)
  geolocator: ^9.0.2           # Untuk lokasi GPS jika digunakan di peta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - lib/app/core/assets/map.png
  - lib/app/core/assets/qris.png


  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
